version: "3.8"

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bvt_auth
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./back-end/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./back-end/db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
volumes:
  mysql_data:
