
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bvt_auth
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./back-end/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./back-end/db/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  # ChatGPT reccomends this code
  # app:
  #   build: .
  #   environment:
  #     host: mysql
  #     user: user
  #     password: password
  #     port: 3306
  #     database: bvt_auth
  #     ACCESS_TOKEN_SECRET: dowYzS+LKidwNwQsPXn1Wswfj4YujivVyn8dzWdL+p0=
  #     REFRESH_TOKEN_SECRET: qGAzyqZldHi06ibEwkqzWhUq19JgB+vX++MNmC8n+e0=
  #     SERVER_PORT: 4000
  #   depends_on:
  #     - mysql
  #   ports:
  #     - "4000:4000"
  # ChatGPT reccomends this code


volumes:
  mysql_data:
